# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: good_live_development
  host: 127.0.0.1
  username: good_live

test:
  adapter: mysql
  database: good_live_test
  host: 127.0.0.1
  username: good_live

production:
  adapter: mysql
  database: good_live_production
  host: 127.0.0.1
  username: good_live
